### ISSUE TITLE
Website todo

### ISSUE THREAD

**Issue by mherchel** [Gainesville-Barcamp/Barcamp-2018#1]
## Housekeeping

- [x] Update all event dates to April 21st, 2018
- [x] Update all registration links to https://www.eventbrite.com/e/gainesville-barcamp-2018-tickets-42820940586?aff=es2#tickets
- [x] Update social media share image
- [x] Verify social media meta tags
- [x] Verify twitter card
- [x] Update FAQs
- [x] Clear Sponsors
- [x] Clear Speakers
- [x] Clear Sessions
- [x] Update Prospectus
- [ ] ~Update speaker registration at https://docs.google.com/forms/d/e/1FAIpQLSfmXEtFY0Ux8-TMJxHs2XvN81_uf0f_CwinMuqsK7oUN4b-Sw/viewform~
- [ ] Redirect `Volunteer` and `Speaker` links to EventBrite registration. Speakers need a special code to unlock the speaker registration, and that code is...`speaker`.
- [x] Update FAQ to say that food will be provided. Delicious food.

## Technical

- [x] Convert griddy stuff to CSS Grid

**Comment by tillydray** [comment]
I added the last two items (Redirect Volunteer and Speaker links, and Update FAQ about food), and marked out updating the speaker registration.
